[urls]
forum = 'https://thesouthpacific.org'
rmb = 'https://www.nationstates.net/page=display_region_rmb/region=the_south_pacific'
discord = 'https://discordapp.com/invite/tEyyDyh'

community_std = 'https://www.nationstates.net/page=dispatch/id=1880983'

f_get_involved = 'https://thesouthpacific.org/w/get-involved'
f_legislator_app = 'https://thesouthpacific.org/t/draft-office-of-legislator-applications/4111/1'
f_signup = 'https://thesouthpacific.org/signup'

roleplay_intro = 'https://wiki.thesouthpacific.org/w/Guide:_Getting_started_in_roleplay'
f_roleplay = 'https://thesouthpacific.org/c/pacifica/13'
roleplay_discord = 'https://discord.gg/58aX2yhmqF'
wiki = 'https://wiki.thesouthpacific.org/w/Main_Page'

f_assembly_intro = 'https://thesouthpacific.org/t/assembly-concourse/4666'
f_assembly_guide = 'https://thesouthpacific.org/t/legislators-guide-getting-started-within-the-assembly/2745'
f_election_archive = 'https://thesouthpacific.org/c/elections-archive/35'
f_private_assembly_hall = 'https://thesouthpacific.org/c/assembly/private-hall/9'
f_voting_floor = 'https://thesouthpacific.org/c/assembly/voting-floor/34'
f_cabinet = 'https://thesouthpacific.org/c/cabinet/10'
f_cabinet_orders = 'https://thesouthpacific.org/t/cabinet-and-executive-orders/91'
f_matt_duck = 'https://thesouthpacific.org/t/law-and-treaty-index/2093'
f_hc = 'https://thesouthpacific.org/c/high-court/11'
f_hc_orcs = 'https://docs.google.com/spreadsheets/d/1pIP64vPL_acGAvIYXo0my6PJkrzCPdVXQxk9TvLr9bM/edit?gid=1426095429#gid=1426095429'
f_spsf = 'https://thesouthpacific.org/c/spsf/21'
f_spsf_intro = 'https://thesouthpacific.org/t/about-the-south-pacific-special-forces/57'
f_security = 'https://thesouthpacific.org/c/regional-security/12'
f_election_central = 'https://thesouthpacific.org/c/election-central/31'

owl_region = 'https://www.nationstates.net/region=the_south_pacific_wa_voting_center'
owl_intro = 'https://www.nationstates.net/page=dispatch/id=1396505'
owl_guide = 'https://www.nationstates.net/page=dispatch/id=1385515'

swan_intro = 'https://www.nationstates.net/page=dispatch/id=1042647'
swan_guide = 'https://www.nationstates.net/page=dispatch/id=1048440'
swan_knights = 'https://www.nationstates.net/page=dispatch/id=1045928'

endo_cap = 'https://www.nationstates.net/page=dispatch/id=1048805'
spcg_intro = 'https://www.nationstates.net/page=dispatch/id=1398091'

card_guide = 'https://www.nationstates.net/page=dispatch/id=1301085'

ns_faq = 'https://www.nationstates.net/page=faq'
ns_wa = 'https://www.nationstates.net/page=un'
